auth-server: http://sso-auth:8083 # sso-server地址

server:
  port: 8080

pooi:
  client:
    client-id: pooi_sso_client_1
    client-secret: pooi_sso_client_1
    user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
    access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
    registered-redirect-uri: http://sso-taobao:8083
  resource:
    jwt:
      key-uri: ${auth-server}/oauth/token_key #解析jwt令牌所需要密钥的地址

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework: debug

